# Generated by github.com/davyxu/tabtoy
Actor {ID: 100 Name: "A" Struct {HP: 100 AttackRate: 0.6} BuffID: 0 BuffID: 0  SkillID: 0}
Actor {ID: 101 Name: "B" Struct {AttackRate: 0.8} BuffID: 3 BuffID: 1 Type: Power SkillID: 1 SkillID: 2 SkillID: 3}
Actor {ID: 102 Name: "C" Struct {HP: 123 AttackRate: 0.7} BuffID: 0 BuffID: 0  SkillID: 0 StrStruct {HP: 2 AttackRate: 0.5}}
Actor {ID: 103 Name: "D" Struct {HP: 205} BuffID: 0 BuffID: 0 Type: Power SkillID: 0}
Actor {ID: 104 Name: "E" Struct {AttackRate: 1} BuffID: 0 BuffID: 0  SkillID: 0}
