# Generated by github.com/davyxu/tabtoy
Actor {ID: 100 Name: "黑猫警长" Struct {HP: 100 AttackRate: 0.6} BuffID: 0 BuffID: 0  SkillID: 4 SkillID: 6 SkillID: 7}
Actor {ID: 101 Name: "葫芦\n娃" Struct {AttackRate: 0.8} BuffID: 3 BuffID: 1 Type: Power SkillID: 1}
Actor {ID: 102 Name: "舒\"克\"" Struct {AttackRate: 0.7} BuffID: 0 BuffID: 0  SkillID: 0 StrStruct {HP: 2 AttackRate: 0.5}}
Actor {ID: 103 Name: "贝\n塔" Struct {HP: 205} BuffID: 0 BuffID: 0  SkillID: 0}
Actor {ID: 104 Name: "邋遢大王" Struct {AttackRate: 1} BuffID: 0 BuffID: 0  SkillID: 0}
