// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
package gamedef

import (
	"gamedef"
)

var SampleByID = make(map[int64]*gamedef.ItemDefine)

var SampleByName = make(map[string]*gamedef.ItemDefine)

var ExpByLevel = make(map[int32]*gamedef.ItemDefine)

func MakeConfigIndex(v *gamedef.Config) {

	// Sample
	for _, def := range v.Sample {

		SampleByID[def.ID] = def
		SampleByName[def.Name] = def
	}

	// Exp
	for _, def := range v.Exp {

		ExpByLevel[def.Level] = def
	}

}
