-- Generated by github.com/davyxu/tabtoy
-- Version: 

return {
	init = function( g )
		
		g.ActorType =
		{ 
			None = 0, --  
			Pharah = 1, -- 法鸡 
			Junkrat = 2, -- 狂鼠 
			Genji = 3, -- 源氏 
			Mercy = 4, -- 天使  
			[0] = "None", --  
			[1] = "Pharah", -- 法鸡 
			[2] = "Junkrat", -- 狂鼠 
			[3] = "Genji", -- 源氏 
			[4] = "Mercy", -- 天使 
		}
		return g
	end
}
