-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

return {
	init = function( g )
		g.ExampleKV = { 
			{ ServerIP = "8.8.8.8", ServerPort = 1024, GroupID = {10,20}, },  
		}
		
		return g
	end
}
