// Generated by github.com/davyxu/tabtoy
// Version: 2.2.4
// DO NOT EDIT!!
package table

import (
	"github.com/davyxu/tabtoy/exportorv2/sample/gamedef"
	"fmt"
)

var SampleByID = make(map[int64]*gamedef.SampleDefine)

var SampleByName = make(map[string]*gamedef.SampleDefine)

var ExpByLevel = make(map[int32]*gamedef.ExpDefine)

func init() {

	RegisterIndexEntry("Sample", func(content interface{}) {

		config := content.(*gamedef.Config)

		// Sample
		for _, def := range config.Sample {

			if _, ok := SampleByID[def.ID]; ok {
				panic(fmt.Sprintf("duplicate index in SampleByID: %v", def.ID))
			}

			if _, ok := SampleByName[def.Name]; ok {
				panic(fmt.Sprintf("duplicate index in SampleByName: %v", def.Name))
			}

			SampleByID[def.ID] = def
			SampleByName[def.Name] = def

		}

	})

	RegisterIndexEntry("Exp", func(content interface{}) {

		config := content.(*gamedef.Config)

		// Exp
		for _, def := range config.Exp {

			if _, ok := ExpByLevel[def.Level]; ok {
				panic(fmt.Sprintf("duplicate index in ExpByLevel: %v", def.Level))
			}

			ExpByLevel[def.Level] = def

		}

	})
}
