// Generated by github.com/davyxu/tabtoy
// DO NOT EDIT!!
// Version: 3.0.0
package example

type ActorType int32

const (
	ActorType_Leader = 0 // 唐僧
	ActorType_Monkey = 1 // 孙悟空
	ActorType_Pig    = 2 // 猪八戒
	ActorType_Hammer = 3 // 沙僧
)

var (
	ActorTypeMapperValueByName = map[string]int32{
		"Leader": 0, // 唐僧
		"Monkey": 1, // 孙悟空
		"Pig":    2, // 猪八戒
		"Hammer": 3, // 沙僧
	}

	ActorTypeMapperNameByValue = map[int32]string{
		0: "Leader", // 唐僧
		1: "Monkey", // 孙悟空
		2: "Pig",    // 猪八戒
		3: "Hammer", // 沙僧
	}
)

type SampleDefine struct {
	ID            int64     `tb_name:"唯一ID"`
	Name          string    `tb_name:"名称"`
	IconID        int32     `tb_name:"图标ID"`
	NumericalRate float32   `tb_name:"攻击率"`
	ItemID        int32     `tb_name:"物品id"`
	BuffID        []int32   `tb_name:"BuffID"`
	Type          ActorType `tb_name:"类型"`
	SkillID       []int32   `tb_name:"技能ID列表"`
}

// Combine struct
type Config struct {
	SampleDefine []*SampleDefine // table: SampleDefine
}

//
