package printer

import (
	"bytes"
	"fmt"

	"github.com/davyxu/pbmeta"
	pbprotos "github.com/davyxu/pbmeta/proto"
	"github.com/davyxu/tabtoy/data"
)

type luaWriter struct {
	printer *bytes.Buffer
}

func (self *luaWriter) RepeatedMessageBegin(fd *pbmeta.FieldDescriptor, msg *data.DynamicMessage, msgCount int, indent int) {

	self.printer.WriteString(fmt.Sprintf("%s = {\n", fd.Name()))
}

// Value是消息的字段
func (self *luaWriter) WriteMessage(fd *pbmeta.FieldDescriptor, msg *data.DynamicMessage, indent int) {

	if indent == 1 {
		self.printer.WriteString("{")

	} else {
		self.printer.WriteString(fmt.Sprintf("%s = {", fd.Name()))
	}

	rawWriteMessage(self.printer, self, msg, indent)

	self.printer.WriteString("}")

}

func (self *luaWriter) RepeatedMessageEnd(fd *pbmeta.FieldDescriptor, msg *data.DynamicMessage, msgCount int, indent int) {
	self.printer.WriteString("}")
}

func (self *luaWriter) RepeatedValueBegin(fd *pbmeta.FieldDescriptor) {

}

// 普通值
func (self *luaWriter) WriteValue(fd *pbmeta.FieldDescriptor, value string, indent int) {

	var finalValue string
	switch fd.Type() {
	case pbprotos.FieldDescriptorProto_TYPE_STRING,
		pbprotos.FieldDescriptorProto_TYPE_ENUM:
		finalValue = strEscape(value)
	case pbprotos.FieldDescriptorProto_TYPE_INT64,
		pbprotos.FieldDescriptorProto_TYPE_UINT64:
		finalValue = fmt.Sprintf("\"%s\"", value)
	default:
		finalValue = value
	}

	self.printer.WriteString(fmt.Sprintf("%s = %s", fd.Name(), finalValue))
}

func (self *luaWriter) RepeatedValueEnd(fd *pbmeta.FieldDescriptor) {

}

func (self *luaWriter) WriteFieldSpliter() {

	self.printer.WriteString(", ")
}

func (self *luaWriter) PrintMessage(msg *data.DynamicMessage) {

	self.printer.WriteString("return {\n\n")
	rawWriteMessage(self.printer, self, msg, 0)

	self.printer.WriteString("\n\n}")
}

func NewLuaWriter(printer *bytes.Buffer) IWriter {

	printer.WriteString("-- Generated by github.com/davyxu/tabtoy\n")

	return &luaWriter{
		printer: printer,
	}
}
