-- Generated by github.com/davyxu/tabtoy
-- Version: 

return {
	init = function( g )
		
		g.ExampleData = { 
			{ ID = 100, ID2 = 0, Name = "扎克镇", Rate = 3.14, Accuracy = 1.602176, Type = 2, Skill = {3,1,2}, Buff = 100, TagList = {"a","b"}, Multi = {1,3}, }, 
			{ ID = 200, ID2 = 0, Name = "阿努比斯神庙", Rate = 1.2, Accuracy = 3.14159, Type = 1, Skill = {100,0,90}, Buff = 1, TagList = {"c"}, Multi = {4,0}, }, 
			{ ID = 300, ID2 = 0, Name = "花村", Rate = 79.4, Accuracy = 0, Type = 3, Skill = {}, Buff = 0, TagList = {}, Multi = {}, }, 
			{ ID = 400, ID2 = 0, Name = "艾兴瓦尔德", Rate = 0.63, Accuracy = 0, Type = 4, Skill = {}, Buff = 0, TagList = {}, Multi = {}, },  
		}
		
		g.ExtendData = { 
			{ Additive = 1.1, Index2 = 0, }, 
			{ Additive = 1.2, Index2 = 0, },  
		}
		
		g.ExampleKV = { 
			{ ServerIP = "8.8.8.8", ServerPort = 1024, GroupID = {10,20}, },  
		}
		
		
		-- ExampleData
		g.ExampleDataByID = {}
		for _, rec in pairs(g.ExampleData) do
			g.ExampleDataByID[rec.ID] = rec
		end
		
		-- ExampleData
		g.ExampleDataByID2 = {}
		for _, rec in pairs(g.ExampleData) do
			g.ExampleDataByID2[rec.ID2] = rec
		end
		
		-- ExtendData
		g.ExtendDataByIndex2 = {}
		for _, rec in pairs(g.ExtendData) do
			g.ExtendDataByIndex2[rec.Index2] = rec
		end
		
		
		---@enum main.ActorType
		g.ActorType = { 
			None = 0, --  
			Pharah = 1, -- 法鸡 
			Junkrat = 2, -- 狂鼠 
			Genji = 3, -- 源氏 
			Mercy = 4, -- 天使  
			[0] = "None", --  
			[1] = "Pharah", -- 法鸡 
			[2] = "Junkrat", -- 狂鼠 
			[3] = "Genji", -- 源氏 
			[4] = "Mercy", -- 天使 
		}
		return g
	end
}
