// Generated by github.com/davyxu/tabtoy
// DO NOT EDIT!!
// Version: 3.0.0
package table

type TableMode int32

const (
	TableMode_None     = 0 //
	TableMode_Type     = 1 // 类型表
	TableMode_Data     = 2 // 数据表
	TableMode_KeyValue = 3 // 键值表
)

var (
	TableModeMapperValueByName = map[string]int32{
		"None":     0, //
		"Type":     1, // 类型表
		"Data":     2, // 数据表
		"KeyValue": 3, // 键值表
	}

	TableModeMapperNameByValue = map[int32]string{
		0: "None",     //
		1: "Type",     // 类型表
		2: "Data",     // 数据表
		3: "KeyValue", // 键值表
	}
)

type FieldType struct {
	InputFieldName string `tb_name:"输入字段"`
	GoFieldName    string `tb_name:"Go字段"`
	CSFieldName    string `tb_name:"C#字段"`
	DefaultValue   string `tb_name:"默认值"`
}

type TablePragma struct {
	TableMode     TableMode `tb_name:"模式"`
	TableType     string    `tb_name:"表类型"`
	TableFileName string    `tb_name:"表文件名"`
}

type TableKeyValue struct {
	FieldName     string `tb_name:"字段名"`
	FieldType     string `tb_name:"字段类型"`
	Name          string `tb_name:"标识名"`
	Value         string `tb_name:"值"`
	ArraySplitter string `tb_name:"数组切割"`
}

type ErrorID struct {
	HeaderNotMatchFieldName string
	HeaderFieldNotDefined   string
	DuplicateHeaderField    string
	DuplicateKVField        string
	UnknownFieldType        string
	DuplicateTypeFieldName  string
	EnumValueEmpty          string
	DuplicateEnumValue      string
	InvalidTypeTable        string
	HeaderTypeNotFound      string
}

// Combine struct
type Config struct {
	FieldType []*FieldType // table: FieldType
	ErrorID   []*ErrorID   // table: ErrorID
}

// table: ErrorID
func (self *Config) GetKeyValue_ErrorID() *ErrorID {
	return self.ErrorID[0]
}
