# Generated by github.com/davyxu/tabtoy
Actor { ID: 100, Name: "黑猫警长", NumericalRate: 0.6, BuffID:[ 0, 0 ], Type: Fighter, SkillID:[ 4, 6, 7 ], StrStruct:[ { HP: 3, ExType: Power }, { AttackRate: 3.5 } ] }
Actor { ID: 101, Name: "葫芦\n娃", NumericalRate: 0.8, BuffID:[ 3, 1 ], Type: Power, SkillID:[ 1 ], StrStruct:[ {  }, {  } ] }
Actor { ID: 102, Name: "舒\"克\"", NumericalRate: 0.7, BuffID:[ 0, 0 ], Type: Fighter, SkillID:[ 0 ], StrStruct:[ {  }, {  } ] }
Actor { ID: 103, Name: "贝\n塔", NumericalRate: 0, BuffID:[ 0, 0 ], Type: Fighter, SkillID:[ 0 ], StrStruct:[ {  }, {  } ] }
Actor { ID: 104, Name: "邋遢大王", NumericalRate: 1, BuffID:[ 0, 0 ], Type: Fighter, SkillID:[ 0 ], StrStruct:[ {  }, {  } ] }
