// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using System.IO;

namespace gamedef
{
	
	
	public partial class ConfigFile : tabtoy.DataObject
	{	
		
		// Sample
		public List<SampleDefine> Sample = new List<SampleDefine>();
		
		// Exp
		public List<ExpDefine> Exp = new List<ExpDefine>();
	
		public void Deserialize( tabtoy.DataReader reader )
		{
			
			// Sample
			if ( reader.MatchTag(0x90000))
			{
				reader.ReadList_Struct<SampleDefine>( this.Sample );
			}
			
			// Exp
			if ( reader.MatchTag(0x90001))
			{
				reader.ReadList_Struct<ExpDefine>( this.Exp );
			}
			
		}
	}
	

}
