// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using System.IO;
using tabtoy;

namespace gamedef
{
	
	
	public partial class ExpDefine
	{	
		
		// 唯一ID
		public int Level;
		
		// 名称
		public int Exp;
	
		public void Deserialize( DataReader reader )
		{
				
			// 唯一ID
			this.Level = reader.ReadInt32();
				
			// 名称
			this.Exp = reader.ReadInt32();
			
		}
	}
	
	public partial class SampleCombineFile
	{	
		
		// Table row field
		public List<ExpDefine> Exp = new List<ExpDefine>();

        public void DeserializeExp(DataReader reader)
		{
				
			// Table row field
			{
			    var element = new ExpDefine();
			    element.Deserialize(reader);
			
			    this.Exp.Add(element);
			}

			
		}
	}
	

}
