// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using System.IO;

namespace gamedef
{
	
	
	public partial class ExpDefine : tabtoy.DataObject
	{	
		
		// 唯一ID
		public int Level = 0;
		
		// 名称
		public int Exp = 0;
	
		public void Deserialize( tabtoy.DataReader reader )
		{
			
			// 唯一ID
			if ( reader.MatchTag(0x10000))
			{
				this.Level = reader.ReadInt32( );
			}
			
			// 名称
			if ( reader.MatchTag(0x10001))
			{
				this.Exp = reader.ReadInt32( );
			}
			
		}
	}
	

}
