# Generated by github.com/davyxu/tabtoy
# Version: 2.0.0
Sample { ID: 100, Name: "黑猫警长", NumericalRate: 0.6, ItemID: 100, Type: Fighter, SkillID:[ 4, 6, 7 ], StrStruct:[ { HP: 3, ExType: Power }, { AttackRate: 3.5 } ] }
Sample { ID: 101, Name: "葫芦\n娃", NumericalRate: 0.8, ItemID: 100, BuffID:[ 3, 1 ], Type: Power, SkillID:[ 1 ] }
Sample { ID: 102, Name: "舒\"克\"", NumericalRate: 0.7, ItemID: 100, Type: Fighter }
Sample { ID: 103, Name: "贝\n塔", NumericalRate: 0, ItemID: 100, Type: Fighter }
Sample { ID: 104, Name: "邋遢大王", NumericalRate: 1, ItemID: 100, Type: Fighter }
