// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using System.IO;
using tabtoy;

namespace gamedef
{
	
	public enum ActorType
	{
		
		// 
		Fighter = 0,
		
		// 
		Power = 21,
	
	}
	
	
	public partial class Prop
	{	
		
		// 
		public int HP;
		
		// 
		public float AttackRate;
		
		// 
		public ActorType ExType;
	
		public void Deserialize( DataReader reader )
		{
				
			// 
			this.HP = reader.ReadInt32();
				
			// 
			this.AttackRate = reader.ReadSingle();
				
			// 
			this.ExType = (ActorType)reader.ReadInt32();
			
		}
	}
	
	public partial class SampleDefine
	{	
		
		// 唯一ID
		public long ID;
		
		// 名称
		public string Name;
		
		// 攻击率
		public float NumericalRate;
		
		// 物品id
		public int ItemID;
		
		// BuffID
		public List<int> BuffID = new List<int>();
		
		// 类型
		public ActorType Type;
		
		// 技能ID列表
		public List<int> SkillID = new List<int>();
		
		// 字符串结构
		public List<Prop> StrStruct = new List<Prop>();
	
		public void Deserialize( DataReader reader )
		{
				
			// 唯一ID
			this.ID = reader.ReadInt64();
				
			// 名称
			this.Name = reader.ReadUTF8String();
				
			// 攻击率
			this.NumericalRate = reader.ReadSingle();
				
			// 物品id
			this.ItemID = reader.ReadInt32();
				
			// BuffID
			this.BuffID.Add( reader.ReadInt32() );
				
			// 类型
			this.Type = (ActorType)reader.ReadInt32();
				
			// 技能ID列表
			this.SkillID.Add( reader.ReadInt32() );
				
			// 字符串结构
			{
			    var element = new Prop();
			    element.Deserialize(reader);
			
			    this.StrStruct.Add(element);
			}

			
		}
	}
	
	public partial class SampleCombineFile
	{	
		
		// Table row field
		public List<SampleDefine> Sample = new List<SampleDefine>();

        public void DeserializeSample(DataReader reader)
		{
				
			// Table row field
			{
			    var element = new SampleDefine();
			    element.Deserialize(reader);
			
			    this.Sample.Add(element);
			}

			
		}
	}
	

}
