// Generated by github.com/davyxu/tabtoy
// Version: 2.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using System.IO;

namespace gamedef
{
	
	public enum ActorType
	{
		
		// 
		Fighter = 0,
		
		// 
		Power = 21,
	
	}
	
	
	public partial class Prop : tabtoy.DataObject
	{	
		
		// 
		public int HP = 10;
		
		// 
		public float AttackRate = 0;
		
		// 
		public ActorType ExType = ActorType.Fighter;
	
		public void Deserialize( tabtoy.DataReader reader )
		{
			
			// 
			if ( reader.MatchTag(0x10000))
			{
				this.HP = reader.ReadInt32( );
			}
			
			// 
			if ( reader.MatchTag(0x50001))
			{
				this.AttackRate = reader.ReadFloat( );
			}
			
			// 
			if ( reader.MatchTag(0x80002))
			{
				this.ExType = reader.ReadEnum<ActorType>( );
			}
			
		}
	}
	
	public partial class SampleDefine : tabtoy.DataObject
	{	
		
		// 唯一ID
		public long ID = 0;
		
		// 名称
		public string Name = "";
		
		// 攻击率
		public float NumericalRate = 0;
		
		// 物品id
		public int ItemID = 100;
		
		// BuffID
		public List<int> BuffID = new List<int>();
		
		// 类型
		public ActorType Type = ActorType.Fighter;
		
		// 技能ID列表
		public List<int> SkillID = new List<int>();
		
		// 字符串结构
		public List<Prop> StrStruct = new List<Prop>();
	
		public void Deserialize( tabtoy.DataReader reader )
		{
			
			// 唯一ID
			if ( reader.MatchTag(0x20000))
			{
				this.ID = reader.ReadInt64( );
			}
			
			// 名称
			if ( reader.MatchTag(0x60001))
			{
				this.Name = reader.ReadString( );
			}
			
			// 攻击率
			if ( reader.MatchTag(0x50002))
			{
				this.NumericalRate = reader.ReadFloat( );
			}
			
			// 物品id
			if ( reader.MatchTag(0x10003))
			{
				this.ItemID = reader.ReadInt32( );
			}
			
			// BuffID
			if ( reader.MatchTag(0x10004))
			{
				reader.ReadList_Int32( this.BuffID );
			}
			
			// 类型
			if ( reader.MatchTag(0x80005))
			{
				this.Type = reader.ReadEnum<ActorType>( );
			}
			
			// 技能ID列表
			if ( reader.MatchTag(0x10006))
			{
				reader.ReadList_Int32( this.SkillID );
			}
			
			// 字符串结构
			if ( reader.MatchTag(0x90007))
			{
				reader.ReadList_Struct<Prop>( this.StrStruct );
			}
			
		}
	}
	

}
